export const links = {
  email: 'catalinacobap@gmail.com',
  linkedin: 'https://www.linkedin.com/in/catalina-cobaleda-060650303/',
  upwork: 'https://www.upwork.com/freelancers/~01a71bea1473cd1a4d',
};
export const projects = [
  { name: 'Kai Custom Homes', url: 'https://kai-customhomes.com', image: 'kai' },
  { name: 'Costa Rica Descents', url: 'https://costaricadescents.com', image: 'descents' },
  { name: "Ester’s Place", url: 'https://estersplace.com', image: 'esters' },
  { name: 'Baileyscode', url: 'https://baileyscode.com', image: 'baileys' },
];
export const reviews = [
  "Catalina performed top quality work helping me build and develop a WordPress website using Elementor. She knows WordPress thoroughly and could handle any technical request I asked with daily communication. I'll definitely be hiring her again.",
  'Great work and support. Keep up the good work.',
];
export const content = {
 es: {
  ids: { work: 'trabajo', pricing: 'precios', maintenance: 'mantenimiento', process: 'proceso', about: 'sobre-mi', contact: 'contacto' },
  title: 'Catalina Cobap — Diseño web + desarrollo / Costa Rica',
  announcement: 'Diseño y desarrollo, de la idea al lanzamiento',
  eyebrow: 'Diseño web + desarrollo / Costa Rica',
  hero: 'Sitios web diseñados y desarrollados por una sola persona, de la idea al lanzamiento.',
  sub: 'Sitios nuevos y rediseños completos para negocios y profesionales independientes. En línea en alrededor de semana y media, en español o inglés.',
  cta: 'Cuéntame tu proyecto',
  signature: 'Diseñadora & desarrolladora',
  nav: ['Trabajo', 'Precios', 'Proceso', 'Sobre mí', 'Hablemos'],
  skip: 'Saltar al contenido', menu: 'Navegación principal', language: 'Seleccionar idioma',
  work: 'Trabajo reciente', workSub: 'Proyectos en los que hice el diseño y el desarrollo.', visit: 'Ver sitio',
  projectCopy: [
   ['Construcción de casas a medida', 'Un constructor premium con una presencia a la altura.'],
   ['Turismo', 'Un catálogo grande de tours, organizado para explorar fácilmente.'],
   ['Hospitalidad', 'Un hospedaje bilingüe con una presencia en línea completa.'],
   ['Estudio web · Cofundadora', 'Un estudio web costarricense para turismo y hospitalidad.'],
  ],
  reviews: 'Lo que dicen los clientes', reviewsNote: 'Reseñas originales en inglés', reviewer: 'Cliente en Upwork', reviewService: 'Sitio web y diseño UI/UX', upwork: 'Ver perfil en Upwork',
  audience: 'Con quién trabajo',
  audiences: [
   ['Profesionales independientes', 'Consultores, coaches y especialistas que necesitan un sitio que genere confianza.'],
   ['Negocios pequeños', 'Un primer sitio serio, o uno que por fin esté a la altura del negocio.'],
   ['Startups', 'Un sitio claro para presentar el producto a clientes e inversionistas.'],
   ['Negocios medianos', 'Un rediseño completo cuando el sitio actual se quedó atrás.'],
   ['Empresas grandes', 'Sitios y landing pages para proyectos, lanzamientos o campañas específicas.'],
  ],
  start: '¿Cuál es tu caso?',
  routes: [
   ['Todavía no tengo un sitio web de verdad.', 'Sitio nuevo', 'pricing'],
   ['Mi sitio actual ya no representa mi negocio.', 'Rediseño completo', 'pricing'],
   ['Solo quiero que alguien se encargue de mi sitio.', 'Plan de mantenimiento', 'maintenance'],
   ['Mi proyecto no encaja en ninguno.', 'Cotización personalizada gratis', 'contact'],
  ],
  services: [
   ['Sitio nuevo', 'Para negocios y profesionales que necesitan su primer sitio serio.'],
   ['Rediseño completo', 'Tu sitio actual, reconstruido desde cero con la tecnología que mejor se adapte al proyecto. No un parche sobre lo que ya existe.'],
  ],
  pricing: 'Un sitio a la medida de tu negocio.',
  choose: 'Hablemos de mi sitio', custom: '¿Necesitas más páginas o un proyecto fuera de estos paquetes?', quote: 'Cotización personalizada gratis',
  included: 'Ambos incluyen',
  includes: [
   'En español, inglés o ambos',
   'Un estilo visual editorial hecho para tu negocio: tipografía grande, espacio generoso e imágenes con peso',
   'Redacción de textos a partir de la información que me envíes',
   'Se ve bien en todos los dispositivos: celular, tablet y computadora',
   'Formulario de contacto + botón de WhatsApp, para que tus clientes te escriban con un toque',
   '1 ronda de cambios sobre la dirección visual + 2 rondas sobre el sitio construido',
   'Lanzamiento en tu dominio',
   '30 días de corrección de errores después del lanzamiento',
  ],
  before: 'Antes de empezar, me envías',
  requirements: ['Un documento con tus servicios, precios, datos de contacto y todo lo que el sitio debe decir', 'Tu logo e imágenes'],
  excluded: 'No incluye',
  excludes: ['Fotografía', 'Tienda en línea, blog, integraciones ni funcionalidades a medida', 'Dominio: lo compras y renuevas tú', 'Hosting: incluido solo con el plan de mantenimiento'],
  timeline: 'Tiempo: alrededor de semana y media, una vez recibidos el documento y las imágenes.',
  scope: 'El alcance y el precio final se confirman por escrito antes de empezar.',
  maintenance: 'Después del lanzamiento', plan: 'Plan de mantenimiento', month: 'USD/mes', annual: 'O $400 USD/año (2 meses gratis).',
  maintenanceIncludes: ['Hosting', 'Hasta 1 hora al mes de cambios de textos e imágenes (no acumulable)'],
  extra: 'Tiempo adicional: $20 USD/hora. Las funcionalidades nuevas se cotizan como un proyecto aparte.',
  without: 'Sin el plan, el sitio se hospeda en tu propia cuenta y los cambios se cobran por hora.',
  process: 'Del primer mensaje al lanzamiento.',
  steps: [
   ['Definir', 'Me envías el documento con tu información. Confirmo alcance y precio.'],
   ['Estilo', 'Defino la dirección editorial para tu negocio: tipografía, color y composición. Una ronda de cambios.'],
   ['Desarrollar', 'Redacto los textos y construyo el sitio. Dos rondas de cambios.'],
   ['Lanzar', 'Pruebas, conexión del dominio y puesta en línea.'],
  ],
  about: 'Hola, soy Catalina.',
  bio: [
   'Soy diseñadora y desarrolladora web en Costa Rica.',
   'Empecé haciendo sitios para turismo y hospitalidad, y de ahí nació Baileyscode, el estudio web que cofundé. Hoy trabajo con negocios y profesionales de cualquier industria que necesitan un sitio nuevo o reconstruir el que tienen.',
   'Me encargo del ciclo completo, del primer mensaje al lanzamiento. Un solo contacto, y nada que se pierda entre un diseñador y un desarrollador. La IA es parte de mi proceso, y por eso puedo entregar en días y no en meses.',
  ],
  languages: 'Español (nativo) · Inglés', portrait: 'Retrato de Catalina Cobap, diseñadora y desarrolladora web en Costa Rica',
  faq: 'Preguntas frecuentes',
  faqs: [
   ['¿Cuánto tarda un sitio?', 'Alrededor de semana y media, una vez recibidos el documento y las imágenes.'],
   ['¿Cuántas rondas de cambios incluye?', 'Una sobre la dirección visual y dos sobre el sitio construido. Los cambios sobre algo ya aprobado se cobran aparte.'],
   ['¿Puedo editar el sitio yo mismo?', 'Los cambios de textos e imágenes se hacen con el plan de mantenimiento, o se cobran por hora sin él.'],
   ['¿Tú cubres hosting y dominio?', 'El dominio lo compras y renuevas tú. El hosting se incluye solo con el plan de mantenimiento; si no, va en tu propia cuenta.'],
   ['¿Puedes rediseñar mi sitio actual?', 'Sí. Los rediseños se reconstruyen desde cero, con la tecnología que mejor se adapte al proyecto.'],
  ],
  contact: '¿Necesitas un sitio nuevo o reemplazar el que tienes?',
  contactSub: 'Envíame un mensaje con lo que tienes en mente.',
  name: 'Nombre', email: 'Correo', need: '¿Qué necesitas?', needs: ['Sitio nuevo', 'Rediseño', 'Todavía no sé'], website: 'Sitio actual (opcional)', message: 'Cuéntame sobre el proyecto',
  send: 'Enviar mensaje', sending: 'Enviando…', success: 'Mensaje enviado. Te respondo a tu correo.', error: 'No se pudo enviar el mensaje. Intenta de nuevo o escríbeme a catalinacobap@gmail.com.',
  prefer: '¿Prefieres correo?', back: 'Volver arriba', contactLabel: 'Empecemos por una conversación',
  sectionLabels: ['Trabajo seleccionado', 'Reseñas', 'Para quién', 'Por dónde empezar', 'La inversión', 'Mantenimiento', 'El proceso', 'Sobre mí', 'Antes de empezar', 'Tu próximo sitio'],
  prev: 'Proyecto anterior', next: 'Proyecto siguiente', screenshot: 'Vista del sitio de',
 },
 en: {
  ids: { work: 'work', pricing: 'pricing', maintenance: 'maintenance', process: 'process', about: 'about', contact: 'contact' },
  title: 'Catalina Cobap — Web design + development / Costa Rica',
  announcement: 'Design and development, from first idea to launch',
  eyebrow: 'Web design + development / Costa Rica',
  hero: 'Websites designed and built by one person, from first idea to launch.',
  sub: 'New websites and full redesigns for businesses and independent professionals. Live in about a week and a half, in English or Spanish.',
  cta: 'Tell me about your project', signature: 'Designer & developer',
  nav: ['Work', 'Pricing', 'Process', 'About', 'Let’s talk'],
  skip: 'Skip to content', menu: 'Main navigation', language: 'Select language',
  work: 'Recent work', workSub: 'Projects where I did the design and development.', visit: 'View website',
  projectCopy: [
   ['Custom home building', 'A premium custom home builder with a presence to match.'],
   ['Tourism', 'A large tour catalog, organized for easy discovery.'],
   ['Hospitality', 'A bilingual guesthouse with a complete online presence.'],
   ['Web studio · Co-founder', 'A Costa Rican web studio for tourism and hospitality.'],
  ],
  reviews: 'What clients say', reviewsNote: 'Client reviews', reviewer: 'Client on Upwork', reviewService: 'Website and UI/UX design', upwork: 'View Upwork profile',
  audience: 'Who I work with',
  audiences: [
   ['Independent professionals', 'Consultants, coaches, and specialists who need a site that builds trust.'],
   ['Small businesses', 'A first serious website, or one that finally matches the business.'],
   ['Startups', 'A clear site to present the product to clients and investors.'],
   ['Medium-sized businesses', 'A full redesign when the current site has fallen behind the company.'],
   ['Large companies', 'Sites and landing pages for specific projects, launches, or campaigns.'],
  ],
  start: 'Which one fits you?',
  routes: [
   ["I don’t have a real website yet.", 'New website', 'pricing'],
   ['My current site doesn’t represent my business anymore.', 'Full redesign', 'pricing'],
   ['I just want someone to take care of my site.', 'Maintenance plan', 'maintenance'],
   ['My project doesn’t fit any of these.', 'Free custom quote', 'contact'],
  ],
  services: [
   ['New website', 'For businesses and professionals building their first serious site.'],
   ['Full redesign', 'Your current site rebuilt from scratch, with the technology that best fits the project. Not a patch on what’s already there.'],
  ],
  pricing: 'A website shaped around your business.',
  choose: 'Let’s talk about my site', custom: 'Need more pages, or a project outside these packages?', quote: 'Free custom quote',
  included: 'Both include',
  includes: [
   'In English, Spanish, or both',
   'An editorial visual style built for your business: large type, generous space, and images that carry weight',
   'Copywriting based on the information you send',
   'Looks right on every device: phone, tablet, and desktop',
   'Contact form + WhatsApp button, so clients can reach you in one tap',
   '1 round of revisions on the visual direction + 2 rounds on the built site',
   'Launch on your domain',
   '30 days of bug fixes after launch',
  ],
  before: 'Before we start, you send',
  requirements: ['A document with your services, prices, contact details, and anything the site should say', 'Your logo and images'],
  excluded: 'Not included', excludes: ['Photography', 'Online store, blog, integrations, or custom features', 'Domain: purchased and renewed by you', 'Hosting: included only with the maintenance plan'],
  timeline: 'Timeline: about a week and a half, once I have your document and images.', scope: 'Final scope and price are confirmed in writing before work begins.',
  maintenance: 'After launch', plan: 'Maintenance plan', month: 'USD/month', annual: 'Or $400 USD/year (2 months free).',
  maintenanceIncludes: ['Hosting', 'Up to 1 hour per month of text and image updates (doesn’t roll over)'],
  extra: 'Extra time: $20 USD/hour. New features are quoted as a separate project.', without: 'Without the plan, the site is hosted on your own account and updates are billed per hour.',
  process: 'From first message to launch.',
  steps: [
   ['Define', 'You send the document with your information. I confirm scope and price.'],
   ['Style', 'I define the editorial direction for your business: typography, color, and layout. One round of revisions.'],
   ['Build', 'I write the copy and build the site. Two rounds of revisions.'],
   ['Launch', 'Testing, domain connection, and going live.'],
  ],
  about: 'Hi, I’m Catalina.',
  bio: [
   'I’m a web designer and developer based in Costa Rica.',
   'I started out building sites for tourism and hospitality, which led me to co-found Baileyscode, a web studio. Today I work with businesses and professionals in any industry who need a new website or a full rebuild of the one they have.',
   'I handle the full cycle myself, from the first message to launch. One point of contact, nothing lost between a designer and a developer. AI is part of my workflow, which is how I can deliver in days instead of months.',
  ],
  languages: 'Spanish (native) · English', portrait: 'Portrait of Catalina Cobap, web designer and developer based in Costa Rica',
  faq: 'Frequently asked questions',
  faqs: [
   ['How long does a website take?', 'About a week and a half, once I have your document and images.'],
   ['How many revisions are included?', 'One round on the visual direction and two on the built site. Changes to already-approved work are billed separately.'],
   ['Can I edit the site myself?', 'Text and image updates are handled through the maintenance plan, or billed per hour without it.'],
   ['Do you cover hosting and domain?', 'You buy and renew the domain. Hosting is included only with the maintenance plan; otherwise it goes on your own account.'],
   ['Can you redesign my current site?', 'Yes. Redesigns are rebuilt from scratch, with the technology that best fits the project.'],
  ],
  contact: 'Have a website you need built or replaced?', contactSub: 'Send me a message with what you have in mind.',
  name: 'Name', email: 'Email', need: 'What do you need?', needs: ['New website', 'Redesign', 'Not sure yet'], website: 'Current website (optional)', message: 'Tell me about the project',
  send: 'Send message', sending: 'Sending…', success: 'Message sent. I’ll reply to your email.', error: 'Your message didn’t go through. Try again or write me at catalinacobap@gmail.com.',
  prefer: 'Prefer email?', back: 'Back to top', contactLabel: 'Let’s start with a conversation',
  sectionLabels: ['Selected work', 'Reviews', 'Who it’s for', 'Where to start', 'The investment', 'Maintenance', 'The process', 'About me', 'Before we start', 'Your next website'],
  prev: 'Previous project', next: 'Next project', screenshot: 'Website preview for',
 },
};
